<{{target_tag}} class='pull-right {{target_button_class}}' type='button' data-bs-toggle='offcanvas'
data-bs-target='#{{id}}' aria-controls='{{id}}'>
<has name='icon'>
    <i class='{{icon}}'></i>
</has>
<lang>{{target_button_text}}</lang>
</{{target_tag}}>
<!-- {{id}} -->
<div class='offcanvas w-75 {{class_names}}' tabindex='-1' id='{{id}}'
     aria-labelledby='{{id}}Label'>
    <div class='offcanvas-header'>
        <h5 id='{{id}}Label'>
            <has name='icon'>
                <i class='{{icon}}'></i>
            </has>
            <lang>{{title}}</lang>
        </h5>
        <has name='close_button_show'>
            <button type='button' class='btn-close text-reset {{submit_button_class}}' data-bs-dismiss='offcanvas'
                    aria-label='{{close_button_text}}'></button>
        </has>
    </div>
    <div class='offcanvas-body'>
        <div class='position-relative w-100 h-100'>
            <if condition='flush || save'>
                <div class='btn btn-group-justified sticky-top pull-right gap-2 d-flex'>
                    <if condition='flush'>
                        <button class='{{flush_button_class}} pull-right ' onclick='flushIframe()'>
                            <lang>{{flush_button_text}}</lang>
                        </button>
                    </if>
                    <if condition='save'>
                        <button class='{{submit_button_class}} pull-right' id="{{id}}Save">
                            <lang>{{submit_button_text}}</lang>
                        </button>
                    </if>
                </div>
            </if>
            <iframe id='{{id}}Iframe' class='w-100 h-100'
                    data-src='{{action}}'
                    frameborder='0'></iframe>
        </div>
    </div>
</div>
<script>
    //show.bs.offcanvas
    $(function (){
        $('#{{id}}').on('show.bs.offcanvas', function () {
            let Iframe = $('#{{id}}Iframe')
            Iframe.attr('src', Iframe.attr('data-src'))
        })
    })
</script>
<if condition='flush'>
    <script>
        function flushIframe() {
            showLoading();
            let iframe = $('#{{id}}Iframe');
            iframe.attr('src', iframe.attr('src'))
            hideLoading();
        }
    </script>
</if>
<if condition='save'>
    <script>
        $(function (){
            $('#{{id}}Save').on('click',function () {
                let iframe = $('#{{id}}Iframe');
                <?php if ($save_form): ?>
                let form = iframe.contents().find('body').find('{{save_form}}')[0] ?? undefined;
                <?php else: ?>
                let form = iframe.contents().find('body').find('form')?? undefined;
                <?php endif; ?>
                if (form) {
                    showLoading();
                    if(form.length > 0){
                        for (var i = 0; i < form.length; i++) {
                            console.log(form[i]);
                            form[i].submit();
                        }
                    }else{
                        form.submit()
                    }
                    hideLoading();
                }
            })
        })
    </script>
</if>