<!--
============================================================================================================ 
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Component\view\templates\message.phtml START
============================================================================================================
 -->
<?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
<!--
==============================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Component\view\tpl\\zh_Hans_CN\templates\com_message.phtml END
==============================================================================================================================
-->